# Generated by Django 3.2.8 on 2021-11-12 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_item_item_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_lg_desc',
            field=models.CharField(default='None', max_length=200),
        ),
    ]
